---
- name: Copy cloud provider storage class file
  template:
    src: storage-class.yaml.j2
    dest: ~/storage-class.yaml

- name: Copy cloud provider storage class file to single master
  fetch:
    src: ~/storage-class.yaml
    dest: ~/storage-class.yaml
    flat: yes

- name: Login to Openshift
  command: oc login -u system:admin
  changed_when: false

- name: Switch to default project
  command: oc project default

- name: Check to see if storage class is already created
  command: "oc get storageclass"
  register: storage_class

- name: Create storage class
  command: "oc create -f ~/storage-class.yaml"
  when: "'{{ vcenter_datastore }}' not in storage_class.stdout"
